const actionTypes = {

	// synchronous
	SET_DOMAIN_FILTER: 'SET_DOMAIN_FILTER',
	SET_TOPIC_FILTER: 'SET_TOPIC_FILTER',

	// async
	GET_FEEDBACK_REQUESTED: 'GET_FEEDBACK_REQUESTED',
  GET_FEEDBACK_REJECTED: 'GET_FEEDBACK_REJECTED',
  GET_FEEDBACK_FULFILLED: 'GET_FEEDBACK_FULFILLED',

	GET_DOMAIN_REQUESTED: 'GET_DOMAIN_REQUESTED',
  GET_DOMAIN_REJECTED: 'GET_DOMAIN_REJECTED',
  GET_DOMAIN_FULFILLED: 'GET_DOMAIN_FULFILLED',

  ADD_DOMAIN_REQUESTED: 'ADD_DOMAIN_REQUESTED',
  ADD_DOMAIN_REJECTED: 'ADD_DOMAIN_REJECTED',
  ADD_DOMAIN_FULFILLED: 'ADD_DOMAIN_FULFILLED',


	GET_TOPIC_REQUESTED: 'GET_TOPIC_REQUESTED',
  GET_TOPIC_REJECTED: 'GET_TOPIC_REJECTED',
  GET_TOPIC_FULFILLED: 'GET_TOPIC_FULFILLED',

  ADD_TOPIC_REQUESTED: 'ADD_TOPIC_REQUESTED',
  ADD_TOPIC_REJECTED: 'ADD_TOPIC_REJECTED',
  ADD_TOPIC_FULFILLED: 'ADD_TOPIC_FULFILLED',

	GET_USER_REQUESTED: 'GET_USER_REQUESTED',
  GET_USER_REJECTED: 'GET_USER_REJECTED',
  GET_USER_FULFILLED: 'GET_USER_FULFILLED',

  ADD_USER_REQUESTED: 'ADD_USER_REQUESTED',
  ADD_USER_REJECTED: 'ADD_USER_REJECTED',
  ADD_USER_FULFILLED: 'ADD_USER_FULFILLED',


	GET_OPINION_REQUESTED: 'GET_OPINION_REQUESTED',
  GET_OPINION_REJECTED: 'GET_OPINION_REJECTED',
  GET_OPINION_FULFILLED: 'GET_OPINION_FULFILLED',

  ADD_OPINION_REQUESTED: 'ADD_OPINION_REQUESTED',
  ADD_OPINION_REJECTED: 'ADD_OPINION_REJECTED',
  ADD_OPINION_FULFILLED: 'ADD_OPINION_FULFILLED',

  DOMAIN_ADDED: 'DOMAIN_ADDED',
  TOPIC_ADDED: 'TOPIC_ADDED',
  USER_ADDED: 'USER_ADDED',
  OPINION_ADDED: 'OPINION_ADDED'
};

export default actionTypes;
